package util

enum class NetworkError : Error {
    REQUEST_TIMEOUT,
    BAD_REQUEST,
    UNAUTHORIZED,
    CONFLICT,
    TOO_MANY_REQUESTS,
    NO_INTERNET,
    PAYLOAD_TOO_LARGE,
    SERVER_ERROR,
    SERIALIZATION,
    NOT_FOUND,
    NO_HTTP_CLIENT,
    NO_TOKEN,
    ERROR_READING_FEATURE_FILE,
    ERROR_READING_TEST_INFO_FILE,
    UNKNOWN;
}