name: Package DEB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '16'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Retrieve Project Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q printAppVersion)"
        id: app_version

      - name: Get Version
        run: |
          echo "app_version=${{steps.app_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV

      - name: Print Version
        run: |
          echo "${{env.app_version}}"

      - name: Package DEB
        run: ./gradlew packageDeb

      - name: Publish deb artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/build/compose/binaries/main/deb/xray-importer_1.0.0-1_amd64.deb
          name: xray-importer_1.0.0-1_amd64.deb
          #/home/runner/work/xray-importer/xray-importer/build/compose/binaries/main/deb/xray-importer_1.0.0-1_amd64.deb

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: DEB Package Upload
          branch: main
